name: checkout and install
description: checkout and install for every job

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - name: Install Dependencies
      shell: bash
      run: yarn install --frozen-lockfile
