name: Netlify Basic Demo

on:
  push:
    branches:
      - master
      - development

jobs:
  lint_and_format:
    name: lint & format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Install Dependencies
        uses: ./.github/actions/myAction
      - name: Format Code
        run: yarn format

      - name: Lint Code
        run: yarn lint

  # perform_tests:
  #   name: jest test
  #   needs: lint_and_format
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Test Code
  #       run: yarn test

  # netlify_deploy:
  #   name: deploy
  #   needs: perform_tests
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Deploy to netlify lol
  #       run: echo "welcome to benghazi!!!"
