name: Netlify Basic Demo

on:
  push:
    branches:
      - master
      - development

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Format Code
        run: yarn format

      - name: Lint Code
        run: yarn lint

      - name: Test Code
        run: yarn lint
  netlify_deploy:
    needs: initialize_repo
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to netlify lol
        run: exit 0
