name: Netlify Basic Demo

on:
  push:
    branches:
      - master
      - development

jobs:
  checkout_and_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  lint_and_format:
    needs: checkout_and_install
    runs-on: ubuntu-latest
    steps:
      - name: Format Code
        run: yarn format

      - name: Lint Code
        run: yarn lint

  perform_tests:
    needs: lint_and_format
    runs-on: ubuntu-latest
    steps:
      - name: Test Code
        run: yarn test

  netlify_deploy:
    needs: perform_tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to netlify lol
        run: echo "welcome to benghazi!!!"
